### ISSUE TITLE
fileOpenDialog crash

### ISSUE THREAD

**Issue by quininer** [das-labor/panopticon#128]
OS: ArchLinux
steps to reproduce:
0. `cd pkg/arch && makepkg -si `
1. run `qtpanopticon`
2. `Ctrl-E`

```
(gdb) run
Starting program: /usr/bin/qtpanopticon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeb1d1700 (LWP 15032)]
[New Thread 0x7fffe23a7700 (LWP 15033)]
[New Thread 0x7fffddbff700 (LWP 15034)]
[New Thread 0x7fffdd2fe700 (LWP 15035)]
[New Thread 0x7fffdcabd700 (LWP 15036)]
qml: {"status": "ok", "payload": ["ATmega103","ATmega88","ATmega8","AMD64","IA-32","80286","MOS 6502"]}
file:///usr/lib/qt/qml/QtQuick/Controls/Private/MenuContentItem.qml:178: ReferenceError: Acccessible is not defined
QWidget: Cannot create a QWidget without QApplication

Program received signal SIGABRT, Aborted.
0x00007ffff65ae3c8 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff65ae3c8 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff65af84a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6c9f1e1 in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#3  0x00007fffe767e4b1 in QWidgetPrivate::init(QWidget*, QFlags<Qt::WindowType>) () from /usr/lib/libQt5Widgets.so.5
#4  0x00007fffe7833c53 in QDialog::QDialog(QWidget*, QFlags<Qt::WindowType>) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007fffe9dd91e8 in ?? () from /usr/lib/qt/plugins/platformthemes/KDEPlatformTheme.so
#6  0x00007fffe9dd6c90 in ?? () from /usr/lib/qt/plugins/platformthemes/KDEPlatformTheme.so
#7  0x00007fffe9dd7192 in ?? () from /usr/lib/qt/plugins/platformthemes/KDEPlatformTheme.so
#8  0x00007fffe9dca2ea in ?? () from /usr/lib/qt/plugins/platformthemes/KDEPlatformTheme.so
#9  0x00007fffe1a5d3d7 in ?? () from /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
#10 0x00007fffe1a5cfd4 in ?? () from /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
#11 0x00007fffe1a710fb in ?? () from /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
#12 0x00007fffe1a714a0 in ?? () from /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
#13 0x00007fffe1a6eed5 in ?? () from /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
#14 0x00007fffe1a6fc35 in ?? () from /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
#15 0x00007ffff7320dd4 in QQmlVMEMetaObject::metaCall(QMetaObject::Call, int, void**) () from /usr/lib/libQt5Qml.so.5
#16 0x00007ffff7320ed7 in QQmlVMEMetaObject::metaCall(QMetaObject::Call, int, void**) () from /usr/lib/libQt5Qml.so.5
#17 0x00007ffff737af69 in ?? () from /usr/lib/libQt5Qml.so.5
#18 0x00007ffff72f994e in ?? () from /usr/lib/libQt5Qml.so.5
#19 0x00007ffff72fa805 in ?? () from /usr/lib/libQt5Qml.so.5
#20 0x00007ffff72fb0cd in QV4::QObjectMethod::callInternal(QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#21 0x00007ffff7311aa3 in QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#22 0x00007fffe195b269 in ?? ()
#23 0x00007fffe0c013c8 in ?? ()
#24 0x00007fffed0d8400 in ?? ()
#25 0x0003000000000007 in ?? ()
#26 0x00007ffff72829c3 in QV4::ExecutionContext::newCallContext(QV4::FunctionObject*, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#27 0x00007ffff72b18c7 in ?? () from /usr/lib/libQt5Qml.so.5
#28 0x00007ffff7311f71 in QV4::Runtime::callValue(QV4::ExecutionEngine*, QV4::Value const&, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#29 0x00007fffe195cb38 in ?? ()
#30 0x00007fffed0d8780 in ?? ()
#31 0x00007fffe0c01340 in ?? ()
---Type <return> to continue, or q <return> to quit---
#32 0x00007fffdf041b01 in ?? ()
#33 0x30ce1824e27a7d00 in ?? ()
#34 0x00000001f0c01360 in ?? ()
#35 0x00007fffe0c01338 in ?? ()
#36 0x00007fffe0c01348 in ?? ()
#37 0x00007fffe0c01350 in ?? ()
#38 0x00007fffed0d8400 in ?? ()
#39 0x00007ffff72b210a in ?? () from /usr/lib/libQt5Qml.so.5
#40 0x00007ffff7311571 in QV4::Runtime::callActivationProperty(QV4::ExecutionEngine*, int, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#41 0x00007fffe195b0bb in ?? ()
#42 0x00007fffe0c012c0 in ?? ()
#43 0x00007fffe0c01268 in ?? ()
#44 0x00007fffe0c012a8 in ?? ()
#45 0x00007ffff72829c3 in QV4::ExecutionContext::newCallContext(QV4::FunctionObject*, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#46 0x00007ffff72b18c7 in ?? () from /usr/lib/libQt5Qml.so.5
#47 0x00007ffff73a235f in ?? () from /usr/lib/libQt5Qml.so.5
#48 0x00007ffff73486f6 in QQmlBoundSignalExpression::evaluate(void**) () from /usr/lib/libQt5Qml.so.5
#49 0x00007ffff7348fab in ?? () from /usr/lib/libQt5Qml.so.5
#50 0x00007ffff73857ee in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#51 0x00007ffff732824c in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib/libQt5Qml.so.5
#52 0x00007ffff6ec0c20 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#53 0x00007fffe1ad4be8 in ?? () from /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#54 0x00007ffff6ec131a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#55 0x00007fffe1ad264f in ?? () from /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#56 0x00007fffe1ad4cd5 in ?? () from /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#57 0x00007fffe1ad57b0 in ?? () from /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#58 0x00007ffff737af69 in ?? () from /usr/lib/libQt5Qml.so.5
#59 0x00007ffff72f994e in ?? () from /usr/lib/libQt5Qml.so.5
#60 0x00007ffff72fa805 in ?? () from /usr/lib/libQt5Qml.so.5
#61 0x00007ffff72fb0cd in QV4::QObjectMethod::callInternal(QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#62 0x00007ffff7311aa3 in QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#63 0x00007fffe1a18d26 in ?? ()
---Type <return> to continue, or q <return> to quit---
#64 0x00007fffe1484b68 in ?? ()
#65 0x0003000000000002 in ?? ()
#66 0x00007fffe1637180 in ?? ()
#67 0x30ce1824e27a7d00 in ?? ()
#68 0x00007fffde02e380 in ?? ()
#69 0x30ce1824e27a7d00 in ?? ()
#70 0x00007fffe0c011c8 in ?? ()
#71 0x00007fffe0c011d0 in ?? ()
#72 0x00007fffed0d8400 in ?? ()
#73 0x00007ffff72b210a in ?? () from /usr/lib/libQt5Qml.so.5
#74 0x00007ffff7311aa3 in QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#75 0x00007fffe1a17f9e in ?? ()
#76 0xffffffffffff8c60 in ?? ()
#77 0x0000000000000008 in ?? ()
#78 0x0003000000000002 in ?? ()
#79 0x00007fffffff8c80 in ?? ()
#80 0x00007fffffff8c70 in ?? ()
#81 0x00007ffff6cb5ad5 in QByteArray::reallocData(unsigned int, QFlags<QArrayData::AllocationOption>) () from /usr/lib/libQt5Core.so.5
#82 0x00007ffff7504fe0 in ?? () from /usr/lib/libQt5Qml.so.5
#83 0x0000000000000002 in ?? ()
#84 0x00007ffff6e9ce7f in QMetaObject::method(int) const () from /usr/lib/libQt5Core.so.5
#85 0x30ce1824e27a7d00 in ?? ()
#86 0x00007fffffff8c60 in ?? ()
#87 0x00007fffd848ae98 in ?? ()
#88 0x00007ffff74fee20 in ?? () from /usr/lib/libQt5Qml.so.5
#89 0x00007fffe0c010f8 in ?? ()
#90 0x00007fffed0d8400 in ?? ()
#91 0x00007fffffffb1d0 in ?? ()
#92 0x00007fffdcaef260 in ?? ()
#93 0x0000000000000000 in ?? ()
```

**Comment by flanfly** [comment]
I just installed a Arch VM and built the package with makepkg. Ctrl-E works as expected :(

**Comment by quininer** [comment]
I probably missing some dependencies? :(

**Comment by quininer** [comment]
https://github.com/das-labor/panopticon/blob/master/pkg/arch/PKGBUILD#L39

Because of this, I have to run as root qtpanopticon.

**Comment by flanfly** [comment]
I'm glad you were able to get it running :dancer:!
